SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `PROFANITY` ;
SHOW WARNINGS;
USE `PROFANITY`;

-- -----------------------------------------------------
-- Table `PROFANITY`.`PROFANE_PHRASE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFANITY`.`PROFANE_PHRASE_TYPE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `PROFANITY`.`PROFANE_PHRASE_TYPE` (
  `CODE` VARCHAR(10) NOT NULL ,
  `DESCRIPTION` VARCHAR(255) NOT NULL ,
  `CREATED_DATETIME` DATETIME NOT NULL ,
  PRIMARY KEY (`CODE`))
ENGINE = InnoDB
COMMENT = 'The set of profane phrase types.';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PROFANITY`.`PROFANE_PHRASE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFANITY`.`PROFANE_PHRASE` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `PROFANITY`.`PROFANE_PHRASE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `PROFANE_PHRASE` VARCHAR(255) NOT NULL ,
  `PROFANE_PHRASE_TYPE_CODE` VARCHAR(10) NOT NULL ,
  `CREATED_DATETIME` DATETIME NOT NULL ,
  PRIMARY KEY (`ID`, `PROFANE_PHRASE_TYPE_CODE`),
  CONSTRAINT 
    FOREIGN KEY (`PROFANE_PHRASE_TYPE_CODE` )
    REFERENCES `PROFANITY`.`PROFANE_PHRASE_TYPE` (`CODE` ))
ENGINE = InnoDB
COMMENT = 'Set of forbidden words and phrases for data entry validation';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;