-- User cardpayment
-- Database cardpayment

CREATE SCHEMA IF NOT EXISTS `CARDPAYMENT` ;
USE `CARDPAYMENT`;

-- -----------------------------------------------------
-- Table `CARDPAYMENT`.`TRANSACTION_RECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARDPAYMENT`.`TRANSACTION_RECORD` ;

CREATE TABLE IF NOT EXISTS `CARDPAYMENT`.`TRANSACTION_RECORD` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `CREATED_DATETIME` DATETIME NOT NULL ,
  `PROCESS_GUID` VARCHAR(36) NULL ,
  `TRANSACTION_TYPE` VARCHAR(30) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
COMMENT = 'The requests made to TLG';

-- -----------------------------------------------------
-- Table `CARDPAYMENT`.`PROVIDER_RESPONSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CARDPAYMENT`.`PROVIDER_RESPONSE` ;

CREATE TABLE IF NOT EXISTS `CARDPAYMENT`.`PROVIDER_RESPONSE` (
  `DTYPE` VARCHAR(31) NOT NULL ,
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `ACQUIRER_ID` VARCHAR(1) NULL ,
  `ACQUIRER_NAME` VARCHAR(255) NULL ,
  `CARD_TOKEN` VARCHAR(80) NULL ,
  `CREATED_DATETIME` DATETIME NOT NULL ,
  `ERROR_MESSAGE` VARCHAR(255) NULL ,
  `ERROR_TYPE` VARCHAR(30) NULL ,
  `RESULT_CODE` VARCHAR(5) NULL ,
  `RESPONSE_CODE` VARCHAR(2) NULL ,
  `RESPONSE_RESULT` VARCHAR(40) NULL ,
  `AUTH_CHECKER` VARCHAR(20) NULL ,
  `AVS_ADDRESS_RESPONSE` VARCHAR(20) NULL ,
  `AVS_POSTCODE_RESPONSE` VARCHAR(20) NULL ,
  `CV2_RESPONSE` VARCHAR(20) NULL ,
  `PROVIDER_TRANSACTION_ID` VARCHAR(255) NULL ,
  `PROVIDER_REFERENCE` VARCHAR(50) NULL ,
  `VALIDATION_PASSED` VARCHAR(3) NULL ,
  `TRANSACTION_RECORD_ID` BIGINT NOT NULL ,
  `RAW_RESPONSE` TEXT NOT NULL ,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_TRANSACTION_RECORD_ID`
    FOREIGN KEY (`TRANSACTION_RECORD_ID` )
    REFERENCES `CARDPAYMENT`.`TRANSACTION_RECORD` (`ID` ) )
ENGINE = InnoDB
COMMENT = 'The responses from TLG';
























