<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.virginmoneygiving.com/indexer-service/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="indexer-service"
	targetNamespace="http://www.virginmoneygiving.com/indexer-service/"
	xmlns:xsd1="http://www.virginmoneygiving.com/indexer-service">
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.virginmoneygiving.com/indexer-service/"
			xmlns:Q1="http://www.virginmoneygiving.com/indexer-service">
			<xsd:import schemaLocation="indexer-service.xsd"
				namespace="http://www.virginmoneygiving.com/indexer-service">
			</xsd:import>
		</xsd:schema>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
				namespace="http://www.virginmoneygiving.com/indexer-service"
				schemaLocation="indexer-service.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="updateInIndexRequest">
		<wsdl:part name="updateInIndexMessage" element="xsd1:updateInIndexMessage"></wsdl:part>
	</wsdl:message>
	<wsdl:message name="deleteFromIndexRequest">
		<wsdl:part name="deleteFromIndexMessage" element="xsd1:deleteFromIndexMessage"></wsdl:part>
	</wsdl:message>
	<wsdl:portType name="indexer-service">
		<wsdl:operation name="updateInIndexMessage">
			<wsdl:input message="tns:updateInIndexRequest"></wsdl:input>
		</wsdl:operation>
		<wsdl:operation name="deleteFromIndexMessage">
			<wsdl:input message="tns:deleteFromIndexRequest"></wsdl:input>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="indexer-service-port"
		type="tns:indexer-service">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="updateInIndexMessage">
			<soap:operation
				soapAction="http://www.virginmoneygiving.com/indexer-service/updateInIndexMessage" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="deleteFromIndexMessage">
			<soap:operation
				soapAction="http://www.virginmoneygiving.com/indexer-service/deleteFromIndexMessage" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="indexer-service">
		<wsdl:port binding="tns:indexer-service-port"
			name="indexer-service-port">
			<soap:address location="http://www.virginmoneygiving.com/" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
