# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1237306938);
user_pref("app.update.lastUpdateTime.background-update-timer", 1237306938);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1237306938);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1237306939);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1237306939);
user_pref("browser.download.dir", "C:\\Users\\ipriest\\Downloads");
user_pref("browser.download.folderList", 1);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.7");
user_pref("extensions.enabledItems", "{CAFEEFAC-0015-0000-0016-ABCDEFFEDCBA}:5.0.16,{CAFEEFAC-0016-0000-0007-ABCDEFFEDCBA}:6.0.07,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.7");
user_pref("extensions.lastAppVersion", "3.0.7");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1239898941);
